// Copyright 2026 the go-bananas authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package middleware

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
	"github.com/mikehelmick/go-bananas/logging"
	"github.com/mikehelmick/go-bananas/webctx"
)

// CSPNoncePlaceholder is the token in a Content-Security-Policy template that
// [ContentSecurityPolicy] replaces with the request's nonce.
const CSPNoncePlaceholder = "{{nonce}}"

// ContentSecurityPolicy sets the Content-Security-Policy response header to
// policy on every request. Any occurrence of [CSPNoncePlaceholder] in the
// policy is replaced with the per-request nonce generated by [ProcessNonce],
// so the header and templates (which read the nonce via
// [webctx.NonceFromContext]) share a single nonce:
//
//	r.Use(middleware.ProcessNonce())
//	r.Use(middleware.ContentSecurityPolicy(
//		"default-src 'self'; script-src 'self' 'nonce-{{nonce}}'; object-src 'none'"))
//
// When the policy contains the placeholder, install this middleware after
// [ProcessNonce]. If no nonce is on the context, the nonce'd source entries are
// dropped from the emitted header (and a warning is logged) rather than
// emitting an empty 'nonce-' source.
func ContentSecurityPolicy(policy string) mux.MiddlewareFunc {
	needsNonce := strings.Contains(policy, CSPNoncePlaceholder)

	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			value := policy

			if needsNonce {
				nonce := webctx.NonceFromContext(r.Context())
				if nonce == "" {
					logging.Named(logging.FromContext(r.Context()), "middleware.ContentSecurityPolicy").
						Warn("CSP policy uses the nonce placeholder but no nonce is on the context; " +
							"install ProcessNonce before ContentSecurityPolicy")
					// Drop the whole 'nonce-…' source rather than emit a guessable
					// empty nonce, then tidy the whitespace the removal left behind.
					value = strings.ReplaceAll(value, "'nonce-"+CSPNoncePlaceholder+"'", "")
					value = strings.ReplaceAll(value, CSPNoncePlaceholder, "")
					value = strings.Join(strings.Fields(value), " ")
					value = strings.ReplaceAll(value, " ;", ";")
				} else {
					value = strings.ReplaceAll(value, CSPNoncePlaceholder, nonce)
				}
			}

			w.Header().Set("Content-Security-Policy", value)
			next.ServeHTTP(w, r)
		})
	}
}
