name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
    - cron: '0 0 */1 * *'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Setup GO
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.4'
          check-latest: true

      - name: Download modules
        run: go mod download

      - name: go-test
        shell: bash        
        run: make test-acc

      - name: go-coverage
        shell: bash
        run: |-
          OUTPUT="$(make test-coverage)"
          TOTAL="$(echo $OUTPUT | awk 'END{print $NF}')"
          echo "::group::Coverage (${TOTAL})"
          echo "${OUTPUT}"
          echo "::endgroup::"

  lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - uses: reviewdog/action-setup@v1

      - name: Install pcregrep
        run: sudo apt-get -yqq install pcregrep

      - uses: actions/setup-go@v6
        with:
          go-version: '1.26.4'

      - name: Download modules
        run: go mod download

      - name: go-lint
        shell: bash
        run: |-
          set -eEu
          set +o pipefail
          make lint

      - name: copyright-check
        shell: bash
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: |-
          set -eEu
          set +o pipefail

          # Require a copyright header with any plausible year — existing files
          # keep their original year; only the header's presence is enforced.
          find . -type f -name '*.go' -exec awk 'FNR==1{if ($0!~"Copyright 20[0-9][0-9]" && $0!~"Code generated") print FILENAME ":1:missing copyright header";}' '{}' + | \
          reviewdog -efm="%f:%l:%m" \
            -name="copyright-check" \
            -reporter="github-pr-check" \
            -filter-mode="diff_context" \
            -fail-on-error="true" \
            -level="error"

      - name: generate-check
        shell: bash
        run: |-
          set -eEu
          set +o pipefail
          make generate-check

      - name: tab-check
        shell: bash
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: |-
          set -eEu
          set +o pipefail

          make tabcheck | \
          reviewdog -efm="%f:%l:%m" \
            -name="tab-check" \
            -reporter="github-pr-check" \
            -filter-mode="diff_context" \
            -fail-on-error="true" \
            -level="error"
